### ISSUE TITLE
APM Metrics

### ISSUE THREAD

**Issue by smagnacco** [newrelic/kamon-newrelic-reporter#12]
Great work. Are you planning to do the same for APM metrics?

**Comment by breedx-nr** [comment]
kHi @smagnacco !  Thanks for the interest.  Our short term roadmap for this doesn't yet have sending of traditional APM transaction events (flagging @abhihub here to note this as a request).  

Also, don't be surprised/startled when this repo goes away -- the intention is contribute this back into the main kamon-io org.  😄 👍

**Comment by jkwatson** [comment]
@smagnacco are you asking about kamon apm or NR apm?  We are planning on sending kamon generated metrics to NR, but they will end up in NR as dimensional metrics, which don't currently appear in NR APM, but are visible in Insights and New Relic One.

**Comment by smagnacco** [comment]
Hi, thanks for the response! NR APM!

**Comment by jkwatson** [comment]
Sorry, @smagnacco . I think that the likelihood that we will write metrics that will be visible in the existing NR APM is very very low. I'm going to close this as 'won't do'. If you feel that it is extremely important, please feel free to re-open and we can re-assess. Thanks!
